
version: "3.3"
services:
  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    container_name: crawler
    volumes:
      - ./crawler:/crawler
    working_dir: /crawler
    entrypoint: >
      sh -c "while true; do sleep 1; done;"
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - 3306:3306
    working_dir: /
    entrypoint: >
      sh -c "mysqld"