
version: "3.3"
services:
  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    container_name: crawler
    env_file:
      - docker.env
    volumes:
      - ./crawler:/crawler
    working_dir: /crawler
    entrypoint: >
      sh -c "./twicyrc"
    depends_on:
      - db
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - 3306:3306
    working_dir: /
    env_file:
      - docker.env
    entrypoint: >
      sh -c "mysqld"